CREATE TABLE IF NOT EXISTS "EnergySettings" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "panelPowerW" DOUBLE PRECISION NOT NULL DEFAULT 6000,
    "batteryCapacityWh" DOUBLE PRECISION NOT NULL DEFAULT 10000,
    "gridTariff" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "exportTariff" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "latitude" DOUBLE PRECISION NOT NULL DEFAULT 33.8938,
    "longitude" DOUBLE PRECISION NOT NULL DEFAULT 35.5018,
    "timezone" TEXT NOT NULL DEFAULT 'Asia/Beirut',
    "panelTilt" DOUBLE PRECISION,
    "panelAzimuth" DOUBLE PRECISION,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "EnergySettings_pkey" PRIMARY KEY ("id")
);