ALTER TABLE "InverterConnection"
  ADD COLUMN "serialPort" TEXT,
  ADD COLUMN "port" INTEGER,
  ADD COLUMN "baudRate" INTEGER NOT NULL DEFAULT 9600,
  ADD COLUMN "dataBits" INTEGER NOT NULL DEFAULT 8,
  ADD COLUMN "stopBits" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "parity" TEXT NOT NULL DEFAULT 'N',
  ADD COLUMN "slaveId" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "timeoutMs" INTEGER NOT NULL DEFAULT 3000,
  ADD COLUMN "pollingIntervalMs" INTEGER NOT NULL DEFAULT 10000,
  ADD COLUMN "gatewayUrl" TEXT;