'use client';
import {useEffect,useState} from 'react';
import {Sunrise,Sunset,CloudSun,RefreshCw,AlertTriangle} from 'lucide-react';
import {HourlyChart} from '@/components/hourly-chart';
import {Section} from '@/components/section';
type Weather={daily:{time:string[];weather_code:number[];temperature_2m_max:number[];temperature_2m_min:number[];sunrise:string[];sunset:string[];precipitation_probability_max:number[]};hourly:{time:string[];shortwave_radiation:number[];cloud_cover:number[]}};
const names:Record<number,string>={0:'صحو',1:'غائم جزئيًا',2:'غيوم متفرقة',3:'غائم',45:'ضباب',51:'رذاذ',61:'مطر',71:'ثلج',80:'زخات',95:'عواصف'};
export default function EnergyPage(){
 const [weather,setWeather]=useState<Weather|null>(null); const [error,setError]=useState(false); const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/weather',{cache:'no-store'});if(!r.ok)throw new Error();setWeather(await r.json());setError(false)}catch{setError(true)}finally{setLoading(false)}};
 useEffect(()=>{load();const id=setInterval(load,1800000);return()=>clearInterval(id)},[]); const d=weather?.daily; const h=weather?.hourly;
 return <div className="space-y-4"><div className="flex items-start justify-between gap-3"><div><h1 className="text-2xl font-extrabold">الطاقة</h1><p className="mt-1 text-sm text-slate-500">الطقس والتوقعات تؤثر في تقدير الطاقة الشمسية.</p></div><button onClick={load} className="rounded-xl border border-slate-200 bg-white p-2.5" aria-label="تحديث الطقس"><RefreshCw size={18}/></button></div>
 {loading&&<div className="rounded-2xl bg-white p-5 text-sm text-slate-500">جارٍ تحميل بيانات Open-Meteo…</div>}{error&&<div className="flex gap-2 rounded-2xl border border-red-100 bg-red-50 p-4 text-sm text-red-700"><AlertTriangle size={18}/>لا تتوفر بيانات الطقس حاليًا.</div>}
 {d&&<><div className="flex gap-2 overflow-x-auto pb-1">{d.time.map((day,i)=><div key={day} className={'min-w-40 rounded-2xl border p-4 '+(i===0?'border-blue-200 bg-blue-50':'border-slate-200 bg-white')}><div className="text-xs text-slate-500">{i===0?'اليوم':i===1?'غدًا':i===2?'بعد غد':day}</div><div className="mt-2 flex items-center gap-2"><CloudSun size={20}/><strong>{names[d.weather_code[i]]??'حالة جوية'}</strong></div><div className="mt-2 text-sm">{Math.round(d.temperature_2m_max[i])}° / {Math.round(d.temperature_2m_min[i])}°</div><div className="mt-2 text-xs text-slate-500">احتمال المطر {d.precipitation_probability_max[i]}%</div></div>)}</div>
 <Section title="ما تبقى من اليوم حتى الغروب"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3"><Sunrise size={17}/><span className="mt-2 block text-xs text-slate-500">الشروق</span><strong>{new Date(d.sunrise[0]).toLocaleTimeString('ar-LB',{hour:'2-digit',minute:'2-digit'})}</strong></div><div className="rounded-xl bg-slate-50 p-3"><Sunset size={17}/><span className="mt-2 block text-xs text-slate-500">الغروب</span><strong>{new Date(d.sunset[0]).toLocaleTimeString('ar-LB',{hour:'2-digit',minute:'2-digit'})}</strong></div><div className="rounded-xl bg-emerald-50 p-3 text-emerald-800"><span className="text-xs">كفاية البطارية</span><strong className="mt-2 block">غير محسوبة</strong><span className="text-xs">تحتاج قراءات البطارية والاستهلاك الحقيقية.</span></div></div></Section>
 <Section title="الإشعاع الشمسي المتوقع" subtitle="بيانات Open-Meteo وليست إنتاجًا فعليًا للألواح"><HourlyChart values={(h?.shortwave_radiation??[]).slice(0,24)}/></Section><Section title="الفائض المتوقع"><p className="text-sm text-slate-500">لا يتم اختلاق رقم للفائض. سيُحسب بعد ربط استهلاك المنزل والبطارية والـPV بقراءات زمنية حقيقية.</p></Section></>}</div>;
}